module.exports = {
    registerUser: require('./user/register-user'),
    authenticateUser: require('./user/authenticate-user'),
    retrieveUser: require('./user/retrieve-user'),
    updateUser: require('./user/update-user'),
    unregisterUser: require('./user/unregister-user'),
    // registerVehicle: require('./vehicle/register-vehicle'),
    // retrieveAllVehicles: require('./vehicle/retrieve-all-vehicles'),
    // retrieveVehicle: require('./vehicle/retrieve-vehicle'),
    // updateVehicle: require('./vehicle/update-vehicle'),
    // unregisterVehicle: require('./vehicle/unregister-vehicle'),
    // registerProperty: require('./instrument/register-instrument'),
    // registerPropertyOwner: require('./instrument/register-owner'),
    // retrieveAllProperties: require('./instrument/retrieve-all-properties'),
    // retrieveProperty: require('./instrument/retrieve-property'),
    // updateProperty: require('./instrument/update-property'),
    // unregisterProperty: require('./instrument/unregister-property'),
    // unregisterPropertyOwner: require('./instrument/unregister-owner'),
    registerDrumkit: require('./drumkit/register-drumkit'),
    retrieveDrumkit: require('./drumkit/retrieve-drumkit'),
    retrieveAllDrumkits: require('./drumkit/retrieve-all-drumkits'),
    unregisterDrumkit: require('./drumkit/unregister-drumkit')
}